### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by thejohncrafter** [artemavrin/UE4-DialogueSystem#3]
Hello !

In the project files, you just wrote 

> Copyright 2015 Mavrin Artem. All Rights Reserved.

But I think, because this is an open source project for Unreal, you should add a license : 
- some people may for instance want to create their own paid game using this plugin  -- in this case, you can maybe add some royalties ?
- a license prevents your and the contributor's work from being stolen !
- and Github likes project with open source licences

And... you should update the copyright  : we're now in 2016 :joy:

Tell me what you think about this, I'll google on my side !

**Comment by artemavrin** [comment]
Hello! 
I think we can use MIT License :smile:

**Comment by thejohncrafter** [comment]
Ok, that's perfect, Thank you !
When will you update the copyrights ?

**Comment by artemavrin** [comment]
done) thanks!
