### ISSUE TITLE
Issue with 12.5

### ISSUE THREAD

**Issue by lukesalt2** [artemavrin/UE4-DialogueSystem#7]
_currently installed 12.5, 3d 3rd Person game, Windows 10_
Hi, 
i have an issue with the current version of your plugin, after enabling it in the project and clicking on "Restart", the editor won't start anymore.
Screenshots:
![screenshot_3](https://cloud.githubusercontent.com/assets/19307595/17675855/ee9b2a84-632b-11e6-8081-a5cf93bb46a2.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/19307595/17675856/ee9d316c-632b-11e6-9c73-a67fc5789895.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/19307595/17675857/ee9df3c2-632b-11e6-84da-2a5fa4bfda7c.png)
![screenshot_7](https://cloud.githubusercontent.com/assets/19307595/17675859/eea343cc-632b-11e6-945e-88f8ab430b04.png)
![screenshot_8](https://cloud.githubusercontent.com/assets/19307595/17675858/eea1a968-632b-11e6-9f20-b7fee3666894.png)

Greetings, 
lukesaltweather

**Comment by artemavrin** [comment]
You should build it with some c++ project. There is no binaries files.

**Comment by lukesalt2** [comment]
the download from the official site doesn't work. (with binaries included)
Screenshots with this version:

![issue1](https://cloud.githubusercontent.com/assets/19307595/17677981/8799478a-6335-11e6-8aec-3e363d52958d.png)
![issue2](https://cloud.githubusercontent.com/assets/19307595/17677979/87952790-6335-11e6-8d10-0a16eff7e05c.png)
![issue3](https://cloud.githubusercontent.com/assets/19307595/17677980/8798c3d2-6335-11e6-9995-8475a4076bbe.png)

~lukesaltweather

**Comment by artemavrin** [comment]
unfortunately it's for ue4.11 on the site, if you want to use plugin with 4.12 you should build it.

**Comment by lukesalt2** [comment]
okay, thanks for replying.
